yaml-files:
  - '*.yaml'
  - '*.yml'
  - '.yamllint'

rules:
  anchors: enable
  braces: 
    level: warning
  brackets: 
    level: warning
  colons: 
    level: warning
  commas: enable
  comments:
    level: warning
  comments-indentation:
    level: warning
  document-end: disable
  document-start:
    level: warning
  empty-lines: 
    level: warning
  empty-values: disable
  float-values: disable
  hyphens: enable
  indentation: 
    level: warning
  key-duplicates: enable
  key-ordering: disable
  line-length:
    level: warning
  new-line-at-end-of-file: 
    level: warning
  new-lines: enable
  octal-values: disable
  quoted-strings: disable
  trailing-spaces: 
    level: warning
  truthy:
    level: warning
