apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: Cdk8sAppProxyGenerator
metadata:
  name: web-app-pr-generator
  namespace: default
spec:
  pollInterval: 60m
  source:
    url: https://github.com/PatrickLaabs/cdk8s-sample-deployment-public.git
    path: deployments
  template:
    spec:
      clusterSelector: {}