# The following patch adds the `clusterctl.cluster.x-k8s.io/move-hierarchy` label to the Cdk8sappproxy CRD type.
# Note that this label will be present on the Cdk8sappproxy kind, not Cdk8sappproxy objects themselves.
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    clusterctl.cluster.x-k8s.io/move-hierarchy: "true"
  name: cdk8sappproxies.addons.cluster.x-k8s.io
