//go:build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Cdk8sAppProxy) DeepCopyInto(out *Cdk8sAppProxy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Cdk8sAppProxy.
func (in *Cdk8sAppProxy) DeepCopy() *Cdk8sAppProxy {
	if in == nil {
		return nil
	}
	out := new(Cdk8sAppProxy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Cdk8sAppProxy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Cdk8sAppProxyGenerator) DeepCopyInto(out *Cdk8sAppProxyGenerator) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Cdk8sAppProxyGenerator.
func (in *Cdk8sAppProxyGenerator) DeepCopy() *Cdk8sAppProxyGenerator {
	if in == nil {
		return nil
	}
	out := new(Cdk8sAppProxyGenerator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Cdk8sAppProxyGenerator) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Cdk8sAppProxyGeneratorList) DeepCopyInto(out *Cdk8sAppProxyGeneratorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Cdk8sAppProxyGenerator, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Cdk8sAppProxyGeneratorList.
func (in *Cdk8sAppProxyGeneratorList) DeepCopy() *Cdk8sAppProxyGeneratorList {
	if in == nil {
		return nil
	}
	out := new(Cdk8sAppProxyGeneratorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Cdk8sAppProxyGeneratorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Cdk8sAppProxyGeneratorSpec) DeepCopyInto(out *Cdk8sAppProxyGeneratorSpec) {
	*out = *in
	out.Source = in.Source
	if in.Filters != nil {
		in, out := &in.Filters, &out.Filters
		*out = make([]PRFilter, len(*in))
		copy(*out, *in)
	}
	in.Template.DeepCopyInto(&out.Template)
	if in.PollInterval != nil {
		in, out := &in.PollInterval, &out.PollInterval
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Cdk8sAppProxyGeneratorSpec.
func (in *Cdk8sAppProxyGeneratorSpec) DeepCopy() *Cdk8sAppProxyGeneratorSpec {
	if in == nil {
		return nil
	}
	out := new(Cdk8sAppProxyGeneratorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Cdk8sAppProxyGeneratorStatus) DeepCopyInto(out *Cdk8sAppProxyGeneratorStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastPolledTime != nil {
		in, out := &in.LastPolledTime, &out.LastPolledTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Cdk8sAppProxyGeneratorStatus.
func (in *Cdk8sAppProxyGeneratorStatus) DeepCopy() *Cdk8sAppProxyGeneratorStatus {
	if in == nil {
		return nil
	}
	out := new(Cdk8sAppProxyGeneratorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Cdk8sAppProxyList) DeepCopyInto(out *Cdk8sAppProxyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Cdk8sAppProxy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Cdk8sAppProxyList.
func (in *Cdk8sAppProxyList) DeepCopy() *Cdk8sAppProxyList {
	if in == nil {
		return nil
	}
	out := new(Cdk8sAppProxyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Cdk8sAppProxyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Cdk8sAppProxySpec) DeepCopyInto(out *Cdk8sAppProxySpec) {
	*out = *in
	if in.GitRepository != nil {
		in, out := &in.GitRepository, &out.GitRepository
		*out = new(GitRepositorySpec)
		**out = **in
	}
	in.ClusterSelector.DeepCopyInto(&out.ClusterSelector)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Cdk8sAppProxySpec.
func (in *Cdk8sAppProxySpec) DeepCopy() *Cdk8sAppProxySpec {
	if in == nil {
		return nil
	}
	out := new(Cdk8sAppProxySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Cdk8sAppProxyStatus) DeepCopyInto(out *Cdk8sAppProxyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Cdk8sAppProxyStatus.
func (in *Cdk8sAppProxyStatus) DeepCopy() *Cdk8sAppProxyStatus {
	if in == nil {
		return nil
	}
	out := new(Cdk8sAppProxyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Cdk8sAppProxyTemplate) DeepCopyInto(out *Cdk8sAppProxyTemplate) {
	*out = *in
	in.Metadata.DeepCopyInto(&out.Metadata)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Cdk8sAppProxyTemplate.
func (in *Cdk8sAppProxyTemplate) DeepCopy() *Cdk8sAppProxyTemplate {
	if in == nil {
		return nil
	}
	out := new(Cdk8sAppProxyTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitRepositorySpec) DeepCopyInto(out *GitRepositorySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitRepositorySpec.
func (in *GitRepositorySpec) DeepCopy() *GitRepositorySpec {
	if in == nil {
		return nil
	}
	out := new(GitRepositorySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PRFilter) DeepCopyInto(out *PRFilter) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PRFilter.
func (in *PRFilter) DeepCopy() *PRFilter {
	if in == nil {
		return nil
	}
	out := new(PRFilter)
	in.DeepCopyInto(out)
	return out
}
