name: pr-ci-verify.yml
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  run-ci-verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.4'
      - name: Run ci verify
        run: make pr-ci-verify
