name: scan-images

on:
  schedule:
    - cron: "0 12 * * 1"

# Remove all permissions from GH_TOKEN except metadata.
permissions: {}

jobs:
  scan:
    name: Trivy
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # tag=v7.0.1
    - name: Setup go
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # tag=v7.0.0
      with:
        go-version-file: go.mod
    - name: Run verify container script
      run: make verify-container-images
